# Generated by Django 6.0.6 on 2026-07-07 04:09

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('mascota', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.CharField(blank=True, max_length=20)),
                ('tamano', models.CharField(max_length=20)),
                ('estado', models.CharField(default='buscando', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('contacto', models.TextField(blank=True)),
                ('fotos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('autor_id', models.UUIDField(blank=True, null=True)),
                ('autor_correo', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
