# Generated by Django 6.0.6 on 2026-07-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='publicaciones_alertapatitas',
        ),
    ]
